### ISSUE TITLE
Quelques améliorations possibles au niveau de la qualité du code

### ISSUE THREAD

**Issue by fandolfatto** [Cat-du-Fromage/NavalBattle_DuruzFlorian#1]
Attention mélange français-anglais dans nommage des fonctions. Idem pour les variables. Tout le code (partie technique) est censé être en anglais.
Des constantes pourraient être utilisées pour toutes les valeurs fixes
Dommage que les coordonnées des bateaux soient codées en dur à plusieurs reprises.
Dans la fonction Main(), le menu est répété deux fois : dommage

**Comment by Cat-du-Fromage** [comment]
problème résolu avec la 1.0
